export const DUMMY_DATA = [
  {
    id: 1,
    courseName: "Digital Shopper Journey",
    imageUrl: "https://www.w3schools.com/w3images/lights.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
    ],
  },
  {
    id: 2,
    courseName: "Advanced Python",
    imageUrl: "https://www.w3schools.com/w3images/nature.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Introduction",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 2,
        title: "Data Structures",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 3,
        title: "Object-Oriented Programming",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 4,
        title: "Web Development with Flask",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 5,
        title: "Data Science with Pandas",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
    ],
  },
  {
    id: 3,
    courseName: "React Native Development",
    imageUrl: "https://www.w3schools.com/w3images/mountains.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Getting Started",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 2,
        title: "Components",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 3,
        title: "State and Props",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 4,
        title: "Navigation",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 5,
        title: "Redux",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
    ],
  },
  {
    id: 4,
    courseName: "Machine Learning",
    imageUrl: "https://www.w3schools.com/w3images/forest.jpg",
    currentlyWatching: 0,
    isFree: false,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Introduction to Machine Learning",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 2,
        title: "Supervised Learning",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 3,
        title: "Unsupervised Learning",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 4,
        title: "Reinforcement Learning",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 5,
        title: "Neural Networks",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
    ],
  },
  {
    id: 5,
    courseName: "Web Development",
    imageUrl: "https://www.w3schools.com/w3images/city.jpg",
    currentlyWatching: 0,
    isFree: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    purchased: false,
    playlist: [
      {
        id: 1,
        title: "HTML Basics",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 2,
        title: "CSS Basics",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 3,
        title: "JavaScript Basics",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 4,
        title: "Responsive Design",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 0,
        completed: 0,
      },
      {
        id: 5,
        title: "Web Accessibility",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 0,
        completed: 0,
      },
    ],
  },
];

