export const DUMMY_DATA = [
  {
    id: 1,
    courseName: "Digital Shopper Journey",
    imageUrl: "https://www.w3schools.com/w3images/lights.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 596,
        completed: 596,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 15,
        completed: 15,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        duration: 593,
        completed: 593,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        duration: 47,
        completed: 47,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        duration: 567,
        completed: 567,
      },
    ],
  },
  {
    id: 2,
    courseName: "Advanced Python",
    imageUrl: "https://www.w3schools.com/w3images/nature.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 596,
        completed: 0,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 15,
        completed: 0,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        duration: 593,
        completed: 0,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        duration: 47,
        completed: 0,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        duration: 567,
        completed: 0,
      },
    ],
  },
  {
    id: 3,
    courseName: "React Native Development",
    imageUrl: "https://www.w3schools.com/w3images/mountains.jpg",
    currentlyWatching: 0,
    isFree: true,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 596,
        completed: 0,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 15,
        completed: 0,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        duration: 593,
        completed: 0,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        duration: 47,
        completed: 0,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        duration: 567,
        completed: 0,
      },
    ],
  },
  {
    id: 4,
    courseName: "Machine Learning",
    imageUrl: "https://www.w3schools.com/w3images/forest.jpg",
    currentlyWatching: 0,
    isFree: false,
    purchased: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 596,
        completed: 0,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 15,
        completed: 0,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        duration: 593,
        completed: 0,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        duration: 47,
        completed: 0,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        duration: 567,
        completed: 0,
      },
    ],
  },
  {
    id: 5,
    courseName: "Web Development",
    imageUrl: "https://www.w3schools.com/w3images/city.jpg",
    currentlyWatching: 0,
    isFree: false,
    queries: [{
      id: 1,
      message: "Discover thousands of vector icons for your React Native applications. Browse our extensive directory of icons and find the perfect one for your project.",
      sender: false,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    },
    {
      id: 2,
      message: "We are now binding this to method in our constructor. This works because it will only happen once when the class is constructed",
      sender: true,
      name: "Harshit Omar",
      time: "7 Days ago",
      avatar: ""
    }],
    purchased: false,
    playlist: [
      {
        id: 1,
        title: "Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        duration: 596,
        completed: 0,
      },
      {
        id: 2,
        title: "eCommerce Basics",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        duration: 15,
        completed: 0,
      },
      {
        id: 3,
        title: "Python in Action",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        duration: 593,
        completed: 0,
      },
      {
        id: 4,
        title: "Learn Mobile App",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        duration: 47,
        completed: 0,
      },
      {
        id: 5,
        title: "Optional",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
        duration: 567,
        completed: 0,
      },
    ],
  },
];

